#!/usr/bin/env node
/**
 * Expand the food rows into the shipped database.
 *
 *   node scripts/gen-foods.js   →  web/assets/js/core/foods.js
 *
 * The rows are terse tuples; this turns them into objects, gives each a stable
 * id, and — the part that earns the script — **checks the arithmetic**.
 */
import { writeFile } from 'node:fs/promises';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { FOOD_ROWS } from './data/foods.js';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');

const slug = s => s.toLowerCase().replace(/['’]/g, '')
  .replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');

/**
 * Atwater, with fibre at 2 kcal/g rather than 4.
 *
 * Fibre is a carbohydrate the body does not fully metabolise, and counting it
 * at the full four flagged every vegetable in the database as wrong. Alcohol
 * carries 7 kcal/g and does not appear in the macro columns at all, so those
 * rows are tagged and exempted rather than fudged.
 */
const implied = ({ p, c, f, fibre }) => p * 4 + Math.max(0, c - fibre) * 4 + fibre * 2 + f * 9;

const foods = [];
const problems = [];
const seen = new Set();

for (const [name, category, per, grams, kcal, p, c, f, fibre = 0, tag = null] of FOOD_ROWS) {
  const id = `f-${slug(name)}`;
  if (seen.has(id)) { problems.push(`duplicate: ${name}`); continue; }
  seen.add(id);

  const food = { id, name, category, per, grams, kcal, p, c, f, fibre, ...(tag ? { tag } : {}) };

  if (tag !== 'alcohol' && kcal > 20) {
    const want = implied(food);
    // A label rounds; a row that is 12% out is a typo, and a typo in a food
    // database is a calorie target that is quietly wrong for months.
    if (Math.abs(want - kcal) > kcal * 0.12) {
      problems.push(`${name}: says ${kcal} kcal, macros imply ${Math.round(want)}`);
    }
  }
  if (!grams || grams <= 0) problems.push(`${name}: no serving weight`);
  foods.push(food);
}

foods.sort((a, b) => a.category.localeCompare(b.category) || a.name.localeCompare(b.name));

if (problems.length) {
  console.error(`✗ ${problems.length} problem(s):`);
  for (const p of problems) console.error(`    ${p}`);
  process.exit(1);
}

const byCat = foods.reduce((t, f) => (t[f.category] = (t[f.category] ?? 0) + 1, t), {});
console.log(`${foods.length} foods across ${Object.keys(byCat).length} categories`);
for (const [k, v] of Object.entries(byCat).sort((a, b) => b[1] - a[1])) {
  console.log(`  ${k.padEnd(14)} ${String(v).padStart(4)}`);
}

const file = `/**
 * The food database — ${foods.length} entries.
 *
 * GENERATED by scripts/gen-foods.js from scripts/data/foods.js.
 * Do not edit by hand; change the rows and re-run.
 *
 * Macros are **per serving**, not per 100 g. Per 100 g is precise and useless
 * when the thing in front of you is one egg. \`grams\` is what one serving
 * weighs, so anything can still be scaled by weight when you know it.
 *
 * The generator checks every row's calories against its macros (Atwater, with
 * fibre at 2 kcal/g) and refuses to write the file if any is more than 12% out.
 */
export const FOODS = ${JSON.stringify(foods, null, 0)
  .replace(/^\[/, '[\n  ').replace(/\},\{/g, '},\n  {').replace(/\]$/, ',\n]')};

export const FOOD_CATEGORIES = ${JSON.stringify(Object.keys(byCat).sort())};

/** Per 100 g, derived — some people think in one unit and some in the other. */
export const per100 = f => ({
  kcal: Math.round((f.kcal / f.grams) * 100),
  p: +((f.p / f.grams) * 100).toFixed(1),
  c: +((f.c / f.grams) * 100).toFixed(1),
  f: +((f.f / f.grams) * 100).toFixed(1),
});
`;

await writeFile(join(root, 'web', 'assets', 'js', 'core', 'foods.js'), file);
console.log(`\nwrote web/assets/js/core/foods.js  (${(file.length / 1024).toFixed(0)} KB)`);
